
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
#REST 
rest : 
    type : rest 
    resource : "routing_rest.yml"
    prefix : /api

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
